export const completeFormDefaultValuesForRegistration = {
  // Section 1: Guest Details
  reservation: false,
  reservationSelect: "",
  checkInDate: undefined,
  checkInTime: "",
  departureDate: undefined,
  departureTime: "",
  totalNights: "",
  linkedCompany: false,
  listedCompanySelect: "",
  currencyName: "BDT",
  conversionRate: "1.00",

  // Section 2: Room Details
  roomTypes: "",
  adultPerRoom: "",
  childPerRoom: "",
  roomNumber: "",
  rackRate: "",
  discountType: "",
  discountAmount: "",
  negotiatedRate: "",
  serviceChargeAmount: "",
  serviceChargeEnabled: false,
  vatAmountValue: "",
  vatAmountEnabled: false,
  cityChargeValue: "",
  cityChargeEnabled: false,
  additionalChargesValue: "",
  additionalChargesEnabled: false,
  totalRoomRentAmt: "",
  roomCheckInDate: undefined,
  roomDepartureDate: undefined,
  numberOfNight: "",
  sameAsGlobalDate: false,
  serviceName: "",
  serviceFromDate: undefined,
  serviceToDate: undefined,
  totalServiceAmount: "",

  // Section 3: Additional Information
  marketSegment: "",
  guestSource: "",
  reference: "",
  mealPlan: "",
  posRemarks: "",
  hotelRemarks: "",
  guestRemarks: "",
};

export const ROOM_FIELDS_REGISTRATION = [
  "roomTypes",
  "adultPerRoom",
  "childPerRoom",
  "roomNumber",
  "rackRate",
  "discountType",
  "discountAmount",
  "negotiatedRate",
  "serviceChargeAmount",
  "serviceChargeEnabled",
  "vatAmountValue",
  "vatAmountEnabled",
  "cityChargeValue",
  "cityChargeEnabled",
  "additionalChargesValue",
  "additionalChargesEnabled",
  "totalRoomRentAmt",
  "roomCheckInDate",
  "roomDepartureDate",
  "numberOfNight",
  "sameAsGlobalDate",
  "serviceName",
  "serviceFromDate",
  "serviceToDate",
  "totalServiceAmount",
];

export const ROOM_DETAILS_KEYS_REGISTRATION = [
  "roomTypes",
  "adultPerRoom",
  "childPerRoom",
  "roomNumber",
  "rackRate",
  "discountType",
  "discountAmount",
  "negotiatedRate",
  "serviceChargeAmount",
  "serviceChargeEnabled",
  "vatAmountValue",
  "vatAmountEnabled",
  "cityChargeValue",
  "cityChargeEnabled",
  "additionalChargesValue",
  "additionalChargesEnabled",
  "totalRoomRentAmt",
  "roomCheckInDate",
  "roomDepartureDate",
  "numberOfNight",
  "sameAsGlobalDate",
  "serviceName",
  "serviceFromDate",
  "serviceToDate",
  "totalServiceAmount",
];
