export const COMPLIMENTARY_ITEMS = [
  { id: "pickupDrop", label: "Airport Pick Up & Drop" },
  { id: "airportDrop", label: "Airport Drop" },
  { id: "welcomeFruitBasket", label: "Welcome Fruit Basket in Room" },
  {
    id: "breakfastBuffetAlaCarteOccupancy",
    label: "Buffet Breakfast / A la carte menu (Depend on Occupancy).",
  },
  { id: "afternoonHighTea", label: "After Noon High tea at 4:30pm-6:00pm" },
  { id: "twoBottleMineralWater", label: "2 bottle mineral water" },
  { id: "oneLargeBottleMineralWater", label: "1 Large bottle Mineral Water" },
  { id: "twoPcsLaundryDaily", label: "2pcs Laundry Daily" },
  { id: "dailyNewspaper", label: "Daily Newspaper" },
  { id: "vipFruitBasket", label: "VIP Fruit Basket in Room" },
  { id: "fourBottleMineralWater", label: "4 Bottles Mineral Water" },
  { id: "personalButler", label: "Personal Butler" },
  { id: "poolGymAccess", label: "Access to Swimming Pool & Health Club/Gym" },
  {
    id: "wifiEverywhere",
    label: "Wi-Fi Internet Access in Room, Restaurant & Lobby",
  },
  { id: "tenPercentGrace", label: "10% Discount in The Grace Restaurant" },
  { id: "twentyFourHourRoomService", label: "24 Hour Room Services" },
  { id: "airportPickup", label: "Airport Pickup" },
  { id: "twentyFiveSpa", label: "25% Discount in Apshira Thai Spa" },
  {
    id: "twentyFiveCinnamon",
    label: "25% Discount in Cinnamon A la Carte Menu",
  },
  { id: "twentyFiveOasisAmbon", label: "25% Discount in Oasis Ambon Lounge" },
  { id: "twelvePercentLiquidBar", label: "12% discount in Liquid Bar" },
  {
    id: "fifteenPercentOasisArabian",
    label: "15% Discount in OASIS (Arabian Restaurant)",
  },
  { id: "miniBar", label: "Mini Bar" },
  { id: "buffetLunch", label: "Buffet Lunch" },
  { id: "buffetDinner", label: "Buffet Dinner" },
  {
    id: "complimentaryBreakfastDinner",
    label: "Complimentary Breakfast and Dinner",
  },
  { id: "toBits", label: "To-Bits" },
  {
    id: "breakfastBuffetAlaCarteOccupancy2",
    label: "Buffet Breakfast / A la carte Menu (Depend on Occupancy)",
  },
  { id: "cookiesFruitPlatter", label: "Cookies Platter / Fruit Basket" },
  { id: "complimentaryBreakfast", label: "Complimentary Breakfast" },
  { id: "twoTeaTwoCoffee", label: "2 Tea and 2 Coffee with milk and sugar" },
];
