//    const roomDetailsValues = {
//         roomTypes: form.getValues("roomTypes"),
//         roomQuantity: form.getValues("roomQuantity"),
//         adultPerRoom: form.getValues("adultPerRoom"),
//         childPerRoom: form.getValues("childPerRoom"),
//         roomNumber: form.getValues("roomNumber"),
//         rackRate: form.getValues("rackRate"),
//         discountType: form.getValues("discountType"),
//         discountAmount: form.getValues("discountAmount"),
//         negotiatedRate: form.getValues("negotiatedRate"),
//         serviceChargeAmount: form.getValues("serviceChargeAmount"),
//         serviceChargeEnabled: form.getValues("serviceChargeEnabled"),
//         vatAmountValue: form.getValues("vatAmountValue"),
//         vatAmountEnabled: form.getValues("vatAmountEnabled"),
//         cityChargeValue: form.getValues("cityChargeValue"),
//         cityChargeEnabled: form.getValues("cityChargeEnabled"),
//         additionalChargesValue: form.getValues("additionalChargesValue"),
//         additionalChargesEnabled: form.getValues("additionalChargesEnabled"),
//         totalRoomRentAmt: form.getValues("totalRoomRentAmt"),
//         roomCheckInDate: form.getValues("roomCheckInDate"),
//         roomCheckOutDate: form.getValues("roomCheckOutDate"),
//         numberOfNight: form.getValues("numberOfNight"),
//         extraBed: form.getValues("extraBed"),
//         serviceName: form.getValues("serviceName"),
//         serviceFromDate: form.getValues("serviceFromDate"),
//         serviceToDate: form.getValues("serviceToDate"),
//         totalServiceAmount: form.getValues("totalServiceAmount"),
//       };

// Pushed to github repo =
