export const completeFormDefaultValues = {
  // Section 1: Guest Information
  checkInDate: undefined,
  checkInTime: "",
  checkOutDate: undefined,
  checkOutTime: "",
  totalNights: "",
  title: "",
  //   status: "",
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  country: "",
  reservationMode: "",
  currencyType: "",
  discountRate: "",

  // Section 2: Room Details
  roomTypes: "",
  roomQuantity: "",
  adultPerRoom: "",
  childPerRoom: "",
  roomNumber: "",
  rackRate: "",
  discountType: "",
  discountAmount: "",
  negotiatedRate: "",
  serviceChargeAmount: "",
  serviceChargeEnabled: false,
  vatAmountValue: "",
  vatAmountEnabled: false,
  cityChargeValue: "",
  cityChargeEnabled: false,
  additionalChargesValue: "",
  additionalChargesEnabled: false,
  totalRoomRentAmt: "",
  roomCheckInDate: undefined,
  roomCheckOutDate: undefined,
  numberOfNight: "",
  extraBed: false,
  serviceName: "",
  serviceFromDate: undefined,
  serviceToDate: undefined,
  totalServiceAmount: "",

  //   Last part

  marketSegment: "",
  guestSource: "",
  reference: "",
  mealPlan: "",
  classification: "regular", // Default value as shown in image
  reservationStatus: "waiting", // Default value as shown in image
  bookersName: "",
  hotelRemarks: "",
  guestRemarks: "",
  posRemarks: "",
  isRoomRateShown: false,
};

// global / top of file
export const ROOM_FIELDS = [
  "roomTypes",
  "roomQuantity",
  "adultPerRoom",
  "childPerRoom",
  "roomNumber",
  "rackRate",
  "discountType",
  "discountAmount",
  "negotiatedRate",
  "serviceChargeAmount",
  "serviceChargeEnabled",
  "vatAmountValue",
  "vatAmountEnabled",
  "cityChargeValue",
  "cityChargeEnabled",
  "additionalChargesValue",
  "additionalChargesEnabled",
  "totalRoomRentAmt",
  "roomCheckInDate",
  "roomCheckOutDate",
  "numberOfNight",
  "extraBed",
  "serviceName",
  "serviceFromDate",
  "serviceToDate",
  "totalServiceAmount",
];
