export const completeFormDefaultValuesForGuestDetails = {
  // Section 1: Header
  personAdult: "",
  familyGroupCouple: false,
  personChild: "",

  // Section 2: Individual Guest Information
  title: "",
  firstName: "",
  lastName: "",
  roomNumber: "",
  fullGuestName: "",
  dateOfBirth: undefined,
  gender: "",
  companyName: "",
  address: "",
  email: "",
  profession: "",
  phone: "",
  city: "",
  zipCode: "",
  country: "",
  nationality: "",
  drivingLicence: "",
  nationalId: "",
  visaNumber: "",
  visaIssueDate: undefined,
  visaExpiryDate: undefined,
  passportNo: "",
  passIssueDate: undefined,
  passExpiryDate: undefined,
  blockedGuest: false,
  isContactPerson: false,
  guestDocument: null,
};

export const GUEST_FIELDS = [
  "title",
  "firstName",
  "lastName",
  "roomNumber",
  "fullGuestName",
  "dateOfBirth",
  "gender",
  "companyName",
  "address",
  "email",
  "profession",
  "phone",
  "city",
  "zipCode",
  "country",
  "nationality",
  "drivingLicence",
  "nationalId",
  "visaNumber",
  "visaIssueDate",
  "visaExpiryDate",
  "passportNo",
  "passIssueDate",
  "passExpiryDate",
  "blockedGuest",
  "isContactPerson",
  "guestDocument",
];

export const GUEST_DETAILS_KEYS = [
  "title",
  "firstName",
  "lastName",
  "roomNumber",
  "fullGuestName",
  "dateOfBirth",
  "gender",
  "companyName",
  "address",
  "email",
  "profession",
  "phone",
  "city",
  "zipCode",
  "country",
  "nationality",
  "drivingLicence",
  "nationalId",
  "visaNumber",
  "visaIssueDate",
  "visaExpiryDate",
  "passportNo",
  "passIssueDate",
  "passExpiryDate",
  "blockedGuest",
  "isContactPerson",
  "guestDocument",
];
